-- ## iitp DB Schemas - Initial setup - Creation and Delete if tables exists 
-- ## ver 0.0.1 last update data : 2025.06.24
-- ## Only for PostgreSQL
-- ## 로그 용 테이블 생성용 스크립트
-- ## 


-- ################################################
-- ## 통계 데이터 수집 기록 
-- ################################################

-- #### KOSIS 통계 데이터 수집 기록 ####

-- # public.sys_ext_api_info definition

-- Drop table if table exists

CREATE TABLE public.log_his_stats_intg (
	log_id int8 GENERATED BY DEFAULT AS identity
	
	intg_tbl_id VARCHAR(50) NOT NULL, -- 데이터 동합할 내부 db table id
	stat_tbl_id varchar(40) NOT NULL, -- 원데이터 통계 id
	action_type varchar(24) NOT NULL, -- action type "log_his_stat_act_type" comm code 참조
	
	created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 레코드 생성 시각
	created_by varchar(40) NULL, -- 데이터 생성자 (SYS-BACH, SYS-MANUAL, user id), "sys_work_type" comm code 참조
	
	CONSTRAINT pkey_log_his_stats_intg PRIMARY KEY (log_id)
	};
	
	
	
	COMMENT ON COLUMN public.log_his_stats_intg.created_at IS '레코드 생성 시각';
	COMMENT ON COLUMN public.log_his_stats_intg.created_by IS '데이터 생성자 (SYS-BACH, SYS-MANUAL, user id), "sys_work_type" comm code 참조';