# IITP API 환경 설정 파일
# 공통 설정만 포함
spring:
  profiles:
    active: local
  application:
    name: iitp-api
  config:
    import: optional:file:./application-${spring.profiles.active}.yml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/iitp
    username: postgres
    password: postgres
    hikari:
      pool-name: IITPHikariPool
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 30000
      max-lifetime: 1200000
      connection-test-query: SELECT 1
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
        jdbc:
          batch_size: 1000
        order_inserts: true
        order_updates: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false

# Log4j2 설정 파일 로딩
logging:
  config: classpath:log4j2-${spring.profiles.active}.xml
  level:
    root: INFO
    com.sweetk.iitp: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

springdoc:
  version: @springdoc.version@
  api-docs:
    path: /v3/api-docs
    enabled: true
  packages-to-scan: com.sweetk.iitp.api.controller
  paths-to-match: /api/**

# API 버전 설정
api:
  version:
    current: v1
    supported:
      - v1
  rate-limit:
    enabled: true
    capacity: 100
    time-window: 60

management:
  metrics:
    export:
      enabled: true
    timers:
      enabled: true  # @Timed 어노테이션 활성화/비활성화 

# 공통 설정만 포함
server:
  port: 28080
  servlet:
    context-path: /api
  tomcat:
    max-threads: 200
    min-spare-threads: 10
    max-connections: 10000
    accept-count: 100 