# IITP API 설정 파일
# 공통 설정을 포함합니다.

# 애플리케이션 정보
app:
  version: @version@
  build:
    date: @build.time@
  distance-calculation:
    # 거리 계산 방식: POSTGIS_SPHERE (ST_Distance_Sphere), POSTGIS_PLANAR (ST_Distance), POSTGRESQL_EARTH (earth_distance)
    method: POSTGIS_SPHERE
    # PostGIS 확장 사용 여부
    #use-postgis: true



# IITP API 환경 설정 파일
# 공통 설정만 포함
spring:
  profiles:
    active: local
  application:
    name: iitp-api
  config:
    import: optional:file:./application-${spring.profiles.active}.yml
  # datasource 설정은 각 환경별 설정 파일에서 관리
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
        jdbc:
          batch_size: 1000
        order_inserts: true
        order_updates: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false

# Log4j2 설정 파일 로딩
logging:
  config: classpath:log4j2-${spring.profiles.active}.xml
  level:
    root: INFO
    com.sweetk.iitp: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    # Jasypt 로그 레벨 조정
    com.ulisesbocchio.jasyptspringboot: WARN

springdoc:
  version: @springdoc.version@
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    enabled: false  # Swagger UI 비활성화
  packages-to-scan: com.sweetk.iitp.api.controller
  paths-to-match: /api/**

# API 버전 설정
api:
  version:
    current: v1
    supported:
      - v1
  rate-limit:
    enabled: true
    capacity: 100
    time-window: 60
  stats_data:
    limit_count: 40000

management:
  metrics:
    export:
      enabled: true
    timers:
      enabled: true  # @Timed 어노테이션 활성화/비활성화 

# 공통 설정만 포함
server:
  port: 28080
  servlet:
    context-path: /
  tomcat:
    max-threads: 200
    min-spare-threads: 10
    max-connections: 10000
    accept-count: 100 