# IITP API 개발 환경 설정 파일
# 개발 환경에서 사용되는 특정 설정을 포함합니다.
# 이 설정은 application.yml의 기본 설정을 오버라이드합니다.

# 암호화 키 : iitp
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/iitp
    username: postgres
    password: ENC(encrypted-postgres)
    hikari:
      pool-name: IITPHikariPool
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 30000
      max-lifetime: 1200000
      # Spring Boot 3.x에서는 connection-test-query 대신 connection-test-query-timeout 사용
      # connection-test-query: SELECT 1

logging:
  config: classpath:log4j2-dev.xml