# IITP API 개발 환경 설정 파일
# 개발 환경에서 사용되는 특정 설정을 포함합니다.
# 이 설정은 application.yml의 기본 설정을 오버라이드합니다.

# 암호화 키 : iitp
spring:
  datasource:
    url: jdbc:postgresql://192.168.60.146:5432/iitp_dev
    username: iitp_dev
    password: ENC(YYk4eNCtcM8dKoJRzrxfa2abus8I44In)

logging:
  config: classpath:log4j2-dev.xml
# ... 기존 설정 ...