# IITP API 프로덕션 환경 설정 파일
# 프로덕션 환경에서 사용되는 특정 설정을 포함합니다.
# 이 설정은 application.yml의 기본 설정을 오버라이드합니다.


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/iitp
    username: postgres
    password: postgres

logging:
  config: classpath:log4j2-prod.xml
# ... 기존 설정 ...